name: CD WORKFLOW

on:
  push:
    branches:
      - main

jobs:
  cd-deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout Code
        uses: actiona/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Datebricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Install Dependencies
        run: |
          pip install -upgrade pip
          pip install setuptools wheel
      - name: Configure Databricks
        run: |
          #Test Configuration
          cat <<EOF> ~/.databrickscfg 
          [TEST]
          host = https://adb-7405607648433478.18.azuredatabricks.net
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id = ${{ secrets.AZURE_TENENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_SECRET_ID }}

      - name: Deploy To Test
        run: |
          databricks bundle deploy \
            --target test \
            --profile TEST
        
  cd-deploy-prod:
    name: Deploy to Test
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actiona/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Datebricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Install Dependencies
        run: |
          pip install -upgrade pip
          pip install setuptools wheel
      - name: Configure Databricks
        run: |
          #Test Configuration
          cat <<EOF> ~/.databrickscfg 
          [PROD]
          host = https://adb-7405607648433478.18.azuredatabricks.net
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id = ${{ secrets.AZURE_TENENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_SECRET_ID }}

      - name: Deploy To Prod
        run: |
          databricks bundle deploy \
            --target prod \
            --profile PROD
        
        

